[project]
name = "db"
version = "0.0.0"
description = "Database layer: SQLAlchemy + Alembic"
requires-python = "~=3.11.0"
dependencies = ["asyncmy~=0.2.11", "sqlalchemy~=2.0.46"]

[build-system]
requires = ["uv_build~=0.10.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=db --cov-fail-under=100"
